config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/cities/search/', to: 'cities#search'
  resources :cities
  resources :states
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

# class City < ApplicationRecord
class City < ApplicationRecord
  belongs_to :state, optional: true
  validates :name, :states_id, presence: true
  scope :ordered_by_name, -> { reorder(name: :asc) }

  def states
    @states = State.all
  end

  def state
    State.find(states_id).name
  end

  def self.filter(city_params)
    params = city_params.to_hash
    return City.all.ordered_by_name if params['states_id'].blank? && params['name'].blank?

    @cities = City
    @cities = @cities.where(states_id: params['states_id'].to_i) unless params['states_id'].blank?
    unless params['name'].blank?
      @cities = @cities.where(sanitize_sql_array(['name like ? or name like ? or name like ?', "%#{params['name']}%",
                                                  "#{params['name']}%", "%#{params['name']}"]))
    end

    @cities
  end
end

app/models/state.rb
# frozen_string_literal: true

# Model for State
class State < ApplicationRecord
  has_many :city
  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Rails Application controller
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

# Controller for City domain
class CitiesController < ApplicationController
  before_action :set_city, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  # GET /cities or /cities.json
  def index
    @cities = City.all.paginate(page: params[:page]).ordered_by_name
  end

  # GET /cities/1 or /cities/1.json
  def show; end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit; end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)
    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_url(@city), notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to cities_url(@city), notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /cities/search
  def search
    @cities = if city_params.present?
                City.filter(city_params).paginate(page: params[:page]).ordered_by_name
              else
                City.all.paginate(page: params[:page]).ordered_by_name
              end
    render template: 'cities/index'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # render not_found if City not found
  def render_not_found
    redirect_to '/404'
  end

  # Only allow a list of trusted parameters through.
  def city_params
    params.require(:city).permit(:id, :name, :states_id, :page)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Rails Home controller
class HomeController < ApplicationController
  def index; end
end

app/controllers/states_controller.rb
# frozen_string_literal: true

# Controller for State domain
class StatesController < ApplicationController
  before_action :set_state, only: %i[show edit update destroy]

  # GET /states or /states.json
  def index
    @states = State.all
  end

  # GET /states/1 or /states/1.json
  def show; end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit; end

  # POST /states or /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to state_url(@state), notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to state_url(@state), notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_state
    @state = State.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def state_params
    params.require(:state).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# A general helper for application
module ApplicationHelper
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

# A helper for City Views
module CitiesHelper
  def states
    State.count.positive? ? State.all : []
  end
end

app/helpers/states_helper.rb
# frozen_string_literal: true

# Helper for States View
module StatesHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <div class="city-name">
    <strong>Name:</strong>
    <%= city.name %>
  </div>
  <div class="state-name">
    <strong >State:</strong>
    <%= city.state %>
  </div>
</div>

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this from being saved.</h2>
      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name,"Name:", style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :states_id, "State:", style: "display: block" %>
    <%= form.collection_select(:states_id, states, :id, :name, prompt: true) %>
  </div>
  <div>
    <%= form.submit "Save"%>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editando</h1>
<%= render "form", city: @city %>
<br>
<div>
  <%= link_to "Mostrar", @city %> |
  <%= link_to "Voltar ao índice", cities_path %>
</div>

app/views/cities/index.html.erb
<% unless notice.blank? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<h1 class="text-center">Cities</h1>
<%= form_with(model:@city, url: "/cities/search", method: :get) do |form| %>
  <%= form.fields_for :city do |city_fields| %>
    <div class="row g-3">
      <div class="col">
        <%= city_fields.label :name, "Choose a state:" %>
        <%= city_fields.collection_select(:states_id, states, :id, :name, prompt: "Select") %>
      </div>
      <div class="col">
        <%= city_fields.text_field :name, placeholder: "Type the city name here" %>
        <%= city_fields.submit "Buscar" %>
      </div>
    </div>
  <% end %>
<% end %>
<%= link_to "New", new_city_path , type:"button", class:"btn btn-info btn-sm bi bi-plus" %>
<br/>
<%= link_to "Home", root_path, type:"button", class:"btn btn-info btn-sm bi bi-skip-backward-btn-fill"  %>
<div class="" id="cities">
  <% if @cities.length.positive? %>
    <div class="apple_pagination">
      <div class="page_info">
        <%= page_entries_info @cities %>
      </div>
      <%= will_paginate @cities,:container => false %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">City</th>
          <th scope="col">State</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @cities.each do |city| %>
          <tr>
            <td><%= city.name %></td>
            <td><%= city.state %></td>
            <td class="align-middle">
              <%= link_to 'Show', city, type:"button", class:"btn btn-info btn-sm bi bi-eye-fill" %>
              <%= link_to 'Edit', edit_city_path(city), type:"button", class:"btn btn-info btn-sm bi bi-pencil-fill" %>
              <%= button_to 'Delete', city, method: :delete, type:"button", class:"btn btn-info btn-sm bi bi-trash" %>
            </td>
          </tr>
        <% end %>
      <% else%>
        <tr>
          <td colspan="3">No records found.</td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @cities %>
    </div>
    <%= will_paginate @cities,:container => false %>
  </div>
</div>

app/views/cities/new.html.erb
<h1>New city</h1>
<%= render "form", city: @city %>
<br>
<div>
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @city %>

<div>
  <%= link_to "Editar", edit_city_path(@city) %> |
  <%= link_to "Voltar ao indice.", cities_path %>

  <%= button_to "Excluir", @city, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Welcome to Geo</h1>
<p>Choose an option below:</p>
<%= link_to "States", states_path %>
<br/>
<%= link_to "Cities", cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  </head>
  <body class="m-3">
    <%= yield %>
  </body>
</html>

app/views/states/_form.html.erb
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>      
      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/states/_state.html.erb
<div id="<%= dom_id state %>">
  <p>
    <strong>Name:</strong>
    <%= state.name %>
  </p>

</div>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Show this state", @state %> |
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>States</h1>

<div id="states">
  <% @states.each do |state| %>
    <%= render state %>
    <p>
      <%= link_to "Show this state", state %>
    </p>
  <% end %>
</div>

<%= link_to "New state", new_state_path %>
<br/>
<%= link_to "Home", root_path, type:"button", class:"btn btn-info btn-sm bi bi-skip-backward-btn-fill"  %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @state %>

<div>
  <%= link_to "Edit this state", edit_state_path(@state) %> |
  <%= link_to "Back to states", states_path %>

  <%= button_to "Destroy this state", @state, method: :delete %>
</div>